name: demo setup nodejs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup node-js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: init package.json
        run: npm init -y

      - name: install dependencies
        run: npm install

      - name: check node version
        run: node -v
